### ISSUE TITLE
Return response in error case

### ISSUE THREAD

**Issue by NilsJPWerner** [hashicorp/go-retryablehttp#46]
Right now the retryable client will return nil and the error if a request failed. It would be good to still have access to the response to for example check the status code or any error messages. 

I know I can define a custom error handler to do this, but I think it should be the default behavior.

**Comment by ryanuber** [comment]
Hey @NilsJPWerner,

This matches what Go's standard `net/http` import does and it is intentional that this package matches that behavior. However, we do want to allow users the ability to inspect all available responses, since there are additional cases which could be considered failures in this library. This is why the `ErrorHandler` exists and is implemented separately, rather than returning the response directly.

Hope that makes sense!
